package com.sourav.quotesapp;

public class QuotesData {
    public static String[][] getQuotes() {
        return new String[][]{
            {"Believe you can and you're halfway there.", "Theodore Roosevelt"},
            {"The only way to do great work is to love what you do.", "Steve Jobs"},
            {"Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"},
            {"Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"},
            {"Dream big and dare to fail.", "Norman Vaughan"},
            {"It does not matter how slowly you go as long as you do not stop.", "Confucius"},
            {"Everything you've ever wanted is on the other side of fear.", "George Addair"},
            {"Don't watch the clock; do what it does. Keep going.", "Sam Levenson"},
            {"The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"},
            {"Aim for the moon. If you miss, you may hit a star.", "W. Clement Stone"},
            {"The way to get started is to quit talking and begin doing.", "Walt Disney"},
            {"If you can dream it, you can do it.", "Walt Disney"},
            {"The best way to predict the future is to create it.", "Peter Drucker"},
            {"Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"},
            {"Stay hungry, stay foolish.", "Steve Jobs"},
            {"The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"},
            {"Do what you can, with what you have, where you are.", "Theodore Roosevelt"},
            {"Be the change that you wish to see in the world.", "Mahatma Gandhi"},
            {"Spread love everywhere you go. Let no one ever come to you without leaving happier.", "Mother Teresa"},
            {"The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"},
            {"In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"},
            {"Never let the fear of striking out keep you from playing the game.", "Babe Ruth"},
            {"Money and success don't change people; they merely amplify what is already there.", "Will Smith"},
            {"Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma.", "Steve Jobs"},
            {"Not how long, but how well you have lived is the main thing.", "Seneca"},
            {"If life were predictable it would cease to be life, and be without flavor.", "Eleanor Roosevelt"},
            {"The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", "Henry Ford"},
            {"In order to write about life first you must live it.", "Ernest Hemingway"},
            {"The big lesson in life, baby, is never be scared of anyone or anything.", "Frank Sinatra"},
            {"Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", "Attributed to various sources"},
            {"Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", "Leo Burnett"},
            {"Life is not a problem to be solved, but a reality to be experienced.", "Soren Kierkegaard"},
            {"The unexamined life is not worth living.", "Socrates"},
            {"Turn your wounds into wisdom.", "Oprah Winfrey"},
            {"The way I see it, if you want the rainbow, you gotta put up with the rain.", "Dolly Parton"},
            {"Do all the good you can, for all the people you can, in all the ways you can, as long as you ever can.", "Hillary Clinton"},
            {"Don't settle for what life gives you; make life better and build something.", "Ashton Kutcher"},
            {"Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it'll pay off. It could be in a year, it could be in 30 years. Eventually, your hard work will pay off.", "Kevin Hart"},
            {"Everything negative – pressure, challenges – is all an opportunity for me to rise.", "Kobe Bryant"},
            {"I like criticism. It makes you strong.", "LeBron James"},
            {"You never really learn much from hearing yourself speak.", "George Clooney"},
            {"Life imposes things on you that you can't control, but you still have the choice of how you're going to live through this.", "Celine Dion"},
            {"Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.", "John F. Kennedy"},
            {"Live for each day as if it's your last.", "James Dean"},
            {"Life is a flower of which love is the honey.", "Victor Hugo"},
            {"Keep smiling, because life is a beautiful thing and there's so much to smile about.", "Marilyn Monroe"},
            {"Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "Buddha"},
            {"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", "Dr. Seuss"},
            {"Good friends, good books, and a sleepy conscience: this is the ideal life.", "Mark Twain"},
            {"Life would be tragic if it weren't funny.", "Stephen Hawking"},
            {"Live in the sunshine, swim the sea, drink the wild air.", "Ralph Waldo Emerson"},
            {"The greatest pleasure of life is love.", "Euripides"},
            {"Life is what we make it, always has been, always will be.", "Grandma Moses"},
            {"Life's tragedy is that we get old too soon and wise too late.", "Benjamin Franklin"},
            {"Life is about making an impact, not making an income.", "Kevin Kruse"},
            {"I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"},
            {"Every strike brings me closer to the next home run.", "Babe Ruth"},
            {"Definiteness of purpose is the starting point of all achievement.", "W. Clement Stone"},
            {"We become what we think about.", "Earl Nightingale"},
            {"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", "Mark Twain"},
            {"Life is 10% what happens to me and 90% of how I react to it.", "Charles Swindoll"},
            {"The most common way people give up their power is by thinking they don't have any.", "Alice Walker"},
            {"The mind is everything. What you think you become.", "Buddha"},
            {"The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"},
            {"An unexamined life is not worth living.", "Socrates"},
            {"Eighty percent of success is showing up.", "Woody Allen"},
            {"Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"},
            {"Winning isn't everything, but wanting to win is.", "Vince Lombardi"},
            {"I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"},
            {"Every child is an artist. The problem is how to remain an artist once he grows up.", "Pablo Picasso"},
            {"You can never cross the ocean until you have the courage to lose sight of the shore.", "Christopher Columbus"},
            {"I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"},
            {"Either you run the day, or the day runs you.", "Jim Rohn"},
            {"Whether you think you can or you think you can't, you're right.", "Henry Ford"},
            {"The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"},
            {"Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "Johann Wolfgang von Goethe"},
            {"The best revenge is massive success.", "Frank Sinatra"},
            {"People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "Zig Ziglar"},
            {"Life shrinks or expands in proportion to one's courage.", "Anais Nin"},
            {"If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "Vincent Van Gogh"},
            {"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"},
            {"Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", "Jesus"},
            {"The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"},
            {"Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"},
            {"When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "Erma Bombeck"},
            {"Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "Booker T. Washington"},
            {"Certain things catch your eye, but pursue only those that capture the heart.", "Ancient Indian Proverb"},
            {"Believe you can and you're halfway there.", "Theodore Roosevelt"},
            {"Everything you've ever wanted is on the other side of fear.", "George Addair"},
            {"We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "Plato"},
            {"Teach thy tongue to say \"I do not know,\" and thous shalt progress.", "Maimonides"},
            {"Start where you are. Use what you have. Do what you can.", "Arthur Ashe"},
            {"When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "John Lennon"},
            {"Fall seven times and stand up eight.", "Japanese Proverb"},
            {"When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "Helen Keller"},
            {"Everything has beauty, but not everyone sees it.", "Confucius"},
            {"How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"},
            {"When I let go of what I am, I become what I might be.", "Lao Tzu"},
            {"Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Maya Angelou"},
            {"Happiness is not something readymade. It comes from your own actions.", "Dalai Lama"},
            {"If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", "Sheryl Sandberg"},
            {"First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.", "Aristotle"},
            {"If the wind will not serve, take to the oars.", "Latin Proverb"},
            {"You can't fall if you don't climb. But there's no joy in living your whole life on the ground.", "Unknown"},
            {"We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", "Marie Curie"},
            {"Too many of us are not living our dreams because we are living our fears.", "Les Brown"},
            {"Challenges are what make life interesting and overcoming them is what makes life meaningful.", "Joshua J. Marine"},
            {"If you want to lift yourself up, lift up someone else.", "Booker T. Washington"}
            // ... (The user can add more to reach 1000)
        };
    }
}
